train_dataset:
  dataset:
    name: image-folder-basic
    args:
      root_path_inp: /home/gpu/girish/dataset/OUTDOOR_RGB/low_light/1_200/png/cam1/adobe
      root_path_out: /home/gpu/girish/dataset/OUTDOOR_RGB/well_lit/png/cam1/hist
      split_key: train
      repeat: 20
      patchify: false
      patch_size: 512
  wrapper:
    name: preprocessing
    args:
      patch: true
      psize: [1024, 1024]
      monochrome: false
      amp: 20
  batch_size: 4

val_dataset:
  dataset:
    name: image-folder-basic
    args:
      root_path_inp: /home/gpu/girish/dataset/OUTDOOR_RGB/low_light/1_200/png/cam1/adobe
      root_path_out: /home/gpu/girish/dataset/OUTDOOR_RGB/well_lit/png/cam1/hist
      split_key: test
      repeat: 1
      patchify: true
      patch_size: 1024
  wrapper:
    name: preprocessing
    args:
      patch: false
      monochrome: false
      amp: 20
  batch_size: 4

model:
  name: unet-basic
  args:
    in_channels: 3
    out_channels: 3
    batch_norm: false
    
loss: l1

optimizer:
  name: adam
  args:
    lr: 0.0001
  sd: false
multi_step_lr:
  milestones: [10]
  gamma: 0.1
epoch_max: 20

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

epoch_val: 1
epoch_save: 10