# For experiment 1: Plain left and right concatenation. 
# Modifications made
# - Architecture got changed. (check the email with the keyword pixelshuffle)
# - Added batch norm as well

train_dataset:
  dataset:
    name: image-folder-pair
    args:
      root_path_inp1: /data1/deva/dataset/OUTDOOR_RAW/low_light/cam1
      root_path_inp2: /data1/deva/dataset/OUTDOOR_RAW/low_light/cam2 
      root_path_out: /data1/deva/dataset/OUTDOOR_RAW/low_light/GT_Final
      split_file: 
      split_key: train
      split_ratio: 0.8
      repeat: 30
      patchify: false
      patch_size: 512
      hetero: true
  wrapper:
    name: preprocessing
    args:
      resize: False
      patch: true
      random_crop: False # Not Needed
      amp: True
      psize: [512,512]
      augment_rotate: False
      normalise: False
      equalize: False
      monochrome: False
      stereo: true
      add_noise: False
      raw: true 
      flip: False 
      rsize: 
      hetero: True
  batch_size: 4

val_dataset:
  dataset:
    name: image-folder-pair
    args:
      root_path_inp1: /data1/deva/dataset/OUTDOOR_RAW/low_light/cam1
      root_path_inp2: /data1/deva/dataset/OUTDOOR_RAW/low_light/cam2
      root_path_out: /data1/deva/dataset/OUTDOOR_RAW/low_light/GT_Final
      split_key: test
      repeat: 1
      patchify: false
      patch_size: 512
  wrapper:
    name: preprocessing
    args:
      resize: False
      patch: true
      random_crop: False # Not Needed
      amp: true
      psize: [512, 512]
      augment_rotate: False
      normalise: False
      equalize: False
      monochrome: False
      stereo: true
      add_noise: False
      raw: true 
      flip: False 
      rsize: None 
      hetero: True
  batch_size: 4

model:
  name: unet-basic-PSUpsampling # Upsampling of the image is done using pixelShuffle 
  args:
    in_channels: 8
    out_channels: 12
    batch_norm: false
    
loss: l1

optimizer:
  name: adam
  args:
    lr: 0.0001
  sd: false
multi_step_lr:
  milestones: [10]
  gamma: 0.1
epoch_max: 30

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

epoch_val: 1
epoch_save: 10