train_dataset:
  dataset:
    name: image-folder-pair
    args:
      root_path_inp1: /home/gpu/girish/dataset/MONOCHROME_PNG/low_light/1_200/cam1
      root_path_inp2: /home/gpu/girish/dataset/MONOCHROME_PNG/low_light/1_200/cam2
      root_path_out: /home/gpu/girish/dataset/MONOCHROME_PNG/well_lit/cam1
      split_key: train
      repeat: 30
      patchify: false
      patch_size: 256
  wrapper:
    name: preprocessing
    args:
      patch: true
      psize: [256, 256]
      monochrome: false
      stereo: true
      amp: 20
  batch_size: 8

val_dataset:
  dataset:
    name: image-folder-pair
    args:
      root_path_inp1: /home/gpu/girish/dataset/MONOCHROME_PNG/low_light/1_200/cam1
      root_path_inp2: /home/gpu/girish/dataset/MONOCHROME_PNG/low_light/1_200/cam2
      root_path_out: /home/gpu/girish/dataset/MONOCHROME_PNG/well_lit/cam1
      split_key: test
      repeat: 1
      patchify: true
      patch_size: 256
  wrapper:
    name: preprocessing
    args:
      patch: false
      monochrome: false
      stereo: true
      amp: 20
  batch_size: 8

model:
  name: cfnet
  args:
    maxdisp: 256
    unet: unet-basic
    in_channels: 6
    out_channels: 3
    
loss: warping-l1
delta: 10
weights: [1,1,1,1,1,1,1,1,1]

optimizer:
  name: adam
  args:
    lr: 0.0001
  sd: false
multi_step_lr:
  milestones: [10]
  gamma: 0.1
epoch_max: 20

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

epoch_val: 1
epoch_save: 10